<html>
<head>
<meta charset="utf-8">
<style>

    body {
        width: 40%;
        background-color: #c1c1c1;
    } 
    barra {
        background-color: gray;
    }
    input{
        width: 90%;
        left: 20%;
        font-size: 20px;
    }
</style>    
</head>
<body>
    <div id="barra">
        <form action="">
            <input type="text">
        </form>
    </div>
    <div id="lista">
    
    </div>
</body>
</html>