<html>
<head>
<meta charset="utf-8">
<style>
    
    #busca {
        position: absolute;
        width: 60%;
        height: 5%;
        right: 5%;
        top: 5%;
        background-color: gray;
    }
    
    #pesquisa {
        font-size: 20px;
        position: absolute;
        left: 8%;
        top: 15%;
        height: 70%;
        width: 90%;
    } 
    
</style>
</head>
<body>

<div id="busca">
<!--    <img src=""> -->
    <input type="text" id="pesquisa">
</div>
    
<div id="lista">
    
</div>
    
    
</body>
</html>