<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="../estilos/busca.css">
</head>
<body>
<div id="tudo">
<div id="busca">
    <form id="formulario" method="POST" action= "../php/busca.func.php">
<!--    <img src=""> -->
    <input type="text" id="pesquisa" name="pesquisado">
    <input type="submit" id="btnpesquisa" name="btn_1" value="Pesquisar">  
    </form>  
</div>
    
    
    
   