<html>
<head>
<style>

    body {
        margin: 4%;
        width: 30%;
        height: 100%;
        background-color: #f1f1f1;
        color: #2a2a2a;
        font-family: calibri;
        font-size: 150%;
        font-weight: 100;

    }
    
    li {
        height: 5%;
        width: 80%;
        padding: 10%;
        list-style: none;
        background-color: #cbcbcb;
        color: #2a2a2a;
        transition: 0.2s;
    }
        
    li:hover {
        background-color: #2a2a2a;
        color: #f1f1f1;
        transition: 0.5s;
    }    
    li:active {
        background-color: #505050;
        color: #ffffff;
        transition: 0.5s;
    }
    
    p {
        background-color: #cbcbcb;
        height: 10%;
        padding: 0%;
        margin: 0%;
    }
    
</style>
</head>
<body>

<ul>
    <li>Conta</li>
    <li>Saldo</li>
    <li>Estacionamentos</li>
    <p></p>
    <li>Configurações</li>    
</ul>

    
</body>
</html>